apiVersion: v1
kind: PersistentVolume
metadata:
  name: yolo-ui-pv
spec:
  capacity:
    storage: 5Gi  # Size of the EBS volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Can be 'Delete' as well, depending on your use case
  storageClassName: gp2  # Use the default 'gp2' class for EBS volumes (can change based on your setup)
  awsElasticBlockStore:
    volumeID: vol-xxxxxxxxxxxxxxxxx  # The volume ID of your EBS volume
    fsType: ext4  # Filesystem type for the volume, can be ext4, xfs, etc.

