apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo-ui-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode that matches the PV access mode
  resources:
    requests:
      storage: 5Gi  # Size should match the PV
  storageClassName: gp2  # Should match the storage class name from PV (if defined)

