apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-ui-deployment
  labels:
    app: yolo-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yolo-ui
  template:
    metadata:
      labels:
        app: yolo-ui
    spec:
      containers:
      - name: yolo-ui
        image: kalyan555/yolo-ui:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-ui-service
spec:
  selector:
    app: yolo-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

